### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by mohits19** [cleebp/csc-522-team5#1]
preprocessing lung CT scans

**Comment by cleebp** [comment]
https://www.kaggle.com/jyotiislam/data-science-bowl-2017/full-preprocessing-tutorial/notebook

**Comment by cleebp** [comment]
I'll be working on preprocessing throughout the day in my branch `preprocessing-brian`, actually having some fun with it so hopefully it will all be in a presentable shape tomorrow. I'm using Python 2.7 and my `.gitignore` ignores the `sample_images/` folder needed to run so that we aren't throwing around ~1.8gigs of dicom files in our commits. Once I have preprocessing in a presentable state I'll pull/merge my branch into master and close this thread.

**Comment by mohits19** [comment]
I have finished until resampling properly. I have not opened it a separate branch, just did it locally. I will open that soon. 
Not able to do the 3D plot (computer gets stuck). I guess we don't necessarily need it to work.

**Comment by cleebp** [comment]
Mine is correctly doing the 3D plots but it does take a long time to run, for what we are doing we don't need the 3D plots for ML purposes but they do look pretty cool.

**Comment by cleebp** [comment]
My most recent commit now loops through all patient folders and saves plots of their hu histograms and lung slice images, i save figures at each step in the pre processing cycle (no pre processing, resampled pixels, resampled pixels + normalized + zero centered) so that we can show him the effects of our pre-processing, though obviously we only care about the final processed plots and we can take out the interim steps later.

Note all these plots are saved in a folder called "output/" which i put in my .gitignore so that we arent uploading tons of plots to github over and over again, just know if you want to run it make sure you have an empty output folder in your project's root.

I'll tinker a bit more with this tonight and merge with master once its cleaner.

**Comment by Rishabh2693** [comment]
I have finished till 3d plot, Dont think its needed. Will add my changes to my branch soon.. Just working on my own repo right now locally

**Comment by cleebp** [comment]
Just merged my stuff with master, after we move on from pre processing and shoe prof our results we can take out all the plot printing in steps but I left it in for now, also added timing to keep an eye on how long it takes to run all this - right now pre processing for the 20 sample patients takes about 7 minutes.
