### ISSUE TITLE
Feature Selection

### ISSUE THREAD

**Issue by mohits19** [cleebp/csc-522-team5#4]

**Comment by mohits19** [comment]
I have been trying to run the maxima_divergence() function given in https://www.kaggle.com/wezemer/data-science-bowl-2017/selective-enhancement-filters. 
But it seems like the function is really expensive. My laptop gets stuck. I am able to run div_of_norm_grad() for single values of sigma but running maxima_divergence() for the entire array is causing the problem. Hope someone else had better luck there.

**Comment by cleebp** [comment]
If you commit/push your code to the feature-extraction branch I can pull it down and run it on my lab machine / report back. I'm only going to be in the lab today for the next 2 hours though.

**Comment by cleebp** [comment]
Hey when I run your code I get results like such (it takes ~40 seconds to perform):

`Now performing Feature Extraction on patient 0`
`max:	1.331912`
`std:	0.108164`
`Time to complete Feature Extraction on patient 0: 38.1579999924 seconds.`

Some patients take longer than others, but the average run time per patient on my machine is 40-50 seconds.

**Comment by cleebp** [comment]
I'm not totally sure what the purpose of the maximum divergence work is though, does this produce the features we will feed to either SVM or CNN? It looks like in his code he is then using `mdng` to produce candidates but I dont know what we would do with them, are they whats fed to a classifier? Just trying to understand it all 😃

**Comment by mohits19** [comment]
I am not really sure either!! My best guess is it finds the areas that diverge vastly from most of the pixels. Look at the images in link after this code. Not sure what would be put in a classifier!!

I am trying to extract area and perimeter from image. Those would go easily into a classifier!

**Comment by Rishabh2693** [comment]
I think we can just use area, perimeter and HU.. they seem relevant..

On Apr 12, 2017 4:13 PM, "mohits19" <notifications@github.com> wrote:

I am not really sure either!! My best guess is it finds the areas that
diverge vastly from most of the pixels. Look at the images in link after
this code. Not sure what would be put in a classifier!!

I am trying to extract area and perimeter from image. Those would go easily
into a classifier!

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/cleebp/csc-522-team5/issues/4#issuecomment-293693963>,
or mute the thread

**Comment by mohits19** [comment]
I have been trying these sources to extract area, perimeter etc: https://www.kaggle.com/c/data-science-bowl-2017#tutorial and https://github.com/booz-allen-hamilton/DSB3Tutorial

It looks promising but I can't get anything to work on my laptop! I am going to start working in the library tomorrow morning. That will be more productive.

**Comment by cleebp** [comment]
Yeah thats the official tutorial code, you have to be careful because that was all written for a different scan file format, the issues on its github talk a lot about its problems. I tried following it originally for the ROI selection but kept running into problems due to the different formats and such, all the same the section `Simple classifier based on nodule features` looks like it could be promising. From what I can understand they are looping through found nodules and grabbing features based on that?

**Comment by Rishabh2693** [comment]
https://github.com/rdcolema/dsb/blob/master/preprocess.ipynb
